services:
  mysql-db:
    image: mysql:8
    container_name: mysql_docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: events
    ports:
      - "3307:3306"
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: spring_app
    depends_on:
       mysql-db:
         condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_docker:3306/events?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network: